project:
  type: website
  output-dir: docs

website:
  title: "Dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Penguins.qmd
    right: 
      - text: Main Site
        href: https://tallenvidal1.github.io/
        target: blank

format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

